[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
prover-script = { path = "../prover/script" }
serde_json = "1.0.133"
